#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose

write_files:
  - path: /opt/docker/docker-compose.yml
    content: |
      ${compose_file_content}

runcmd:
  - systemctl start docker
  - systemctl enable docker
  - cd /opt/docker
  - docker-compose up -d